#!/bin/sh
cat ndn-js-header.txt \
  ../../Closure.js \
  ../../NDN.js \
  ../../XpcomTransport.js \
  ../../util/CCNProtocolDTags.js \
  ../../util/CCNTime.js \
  ../../Name.js \
  ../../ContentObject.js \
  ../../encoding/DateFormat.js \
  ../../Interest.js \
  ../../Key.js \
  ../../PublisherID.js \
  ../../PublisherPublicKeyDigest.js \
  ../../FaceInstance.js \
  ../../ForwardingEntry.js \
  ../../encoding/BinaryXMLEncoder.js \
  ../../encoding/BinaryXMLDecoder.js \
  ../../encoding/BinaryXMLStructureDecoder.js \
  ../../encoding/DataUtils.js \
  ../../encoding/MimeTypes.js \
  ../../encoding/EncodingUtils.js \
  ../../security/KeyManager.js \
  ../../securityLib/sha1.js \
  ../../securityLib/sha256.js \
  ../../securityLib/sha512.js \
  ../../securityLib/md5.js \
  ../../securityLib/ripemd160.js \
  ../../securityLib/base64.js \
  ../../securityLib/rsa.js \
  ../../securityLib/rsa2.js \
  ../../securityLib/rsapem-1.1.js \
  ../../securityLib/rsasign-1.2.js \
  ../../securityLib/asn1hex-1.1.js \
  ../../securityLib/x509-1.1.js \
  ../../securityLib/jsbn.js \
  ../../securityLib/jsbn2.js \
  > ndn-js.jsm
